// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrbEMjSYkjL4fIv6fF0bLlPEC_qLQKnEE',
    appId: '1:97774945157:web:7d657d9e83714433af3aec',
    messagingSenderId: '97774945157',
    projectId: 'syedmuhammadproject',
    authDomain: 'syedmuhammadproject.firebaseapp.com',
    storageBucket: 'syedmuhammadproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIsMMiZM6YjvqlcTFh9UDNC8HnK82Eozs',
    appId: '1:97774945157:android:abda9d84d442a0e3af3aec',
    messagingSenderId: '97774945157',
    projectId: 'syedmuhammadproject',
    storageBucket: 'syedmuhammadproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApE2OCDyAA43wc0ZgllnYHI7yiA2lFFOE',
    appId: '1:97774945157:ios:9f09e1dd7fd245f9af3aec',
    messagingSenderId: '97774945157',
    projectId: 'syedmuhammadproject',
    storageBucket: 'syedmuhammadproject.firebasestorage.app',
    iosBundleId: 'com.example.doctorProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApE2OCDyAA43wc0ZgllnYHI7yiA2lFFOE',
    appId: '1:97774945157:ios:9f09e1dd7fd245f9af3aec',
    messagingSenderId: '97774945157',
    projectId: 'syedmuhammadproject',
    storageBucket: 'syedmuhammadproject.firebasestorage.app',
    iosBundleId: 'com.example.doctorProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrbEMjSYkjL4fIv6fF0bLlPEC_qLQKnEE',
    appId: '1:97774945157:web:52ba0b5f15125281af3aec',
    messagingSenderId: '97774945157',
    projectId: 'syedmuhammadproject',
    authDomain: 'syedmuhammadproject.firebaseapp.com',
    storageBucket: 'syedmuhammadproject.firebasestorage.app',
  );
}
