name: spotify_clone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI and state management
  flutter_bloc: ^9.1.0
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  get: ^4.7.2

  # Firebase packages with compatible versions
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6

  # Other dependencies
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  get_it: ^8.0.3
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 300