// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkmnu9875C2KFM6tw6z7myC63p3x81KUc',
    appId: '1:122884213834:web:25c4ed385433952fafaab3',
    messagingSenderId: '122884213834',
    projectId: 'spotify-clone-d53ef',
    authDomain: 'spotify-clone-d53ef.firebaseapp.com',
    storageBucket: 'spotify-clone-d53ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgIPQq8IyKhaYlpT4Mrjda_vx52R0DgNk',
    appId: '1:122884213834:android:2c0169be3ff03107afaab3',
    messagingSenderId: '122884213834',
    projectId: 'spotify-clone-d53ef',
    storageBucket: 'spotify-clone-d53ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7aEZTb8wkoevaY9Z-ef3RqssFGkTU6Kc',
    appId: '1:122884213834:ios:73f7b85bfdc0833dafaab3',
    messagingSenderId: '122884213834',
    projectId: 'spotify-clone-d53ef',
    storageBucket: 'spotify-clone-d53ef.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7aEZTb8wkoevaY9Z-ef3RqssFGkTU6Kc',
    appId: '1:122884213834:ios:73f7b85bfdc0833dafaab3',
    messagingSenderId: '122884213834',
    projectId: 'spotify-clone-d53ef',
    storageBucket: 'spotify-clone-d53ef.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkmnu9875C2KFM6tw6z7myC63p3x81KUc',
    appId: '1:122884213834:web:d2cf7f1222f3dd8fafaab3',
    messagingSenderId: '122884213834',
    projectId: 'spotify-clone-d53ef',
    authDomain: 'spotify-clone-d53ef.firebaseapp.com',
    storageBucket: 'spotify-clone-d53ef.firebasestorage.app',
  );
}
