// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaVyRoQVbxuymAePpcB0rXOvCSvUVdufI',
    appId: '1:156798140605:web:f3259b694ddbce1e05f7d4',
    messagingSenderId: '156798140605',
    projectId: 'peak-catbird-459818-j8',
    authDomain: 'peak-catbird-459818-j8.firebaseapp.com',
    storageBucket: 'peak-catbird-459818-j8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZPW37agQuVHW1W4wEg4B3VSIn5CacBz8',
    appId: '1:156798140605:android:fbd8825e0bdee27b05f7d4',
    messagingSenderId: '156798140605',
    projectId: 'peak-catbird-459818-j8',
    storageBucket: 'peak-catbird-459818-j8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaVyRoQVbxuymAePpcB0rXOvCSvUVdufI',
    appId: '1:156798140605:web:f2d65138949818e505f7d4',
    messagingSenderId: '156798140605',
    projectId: 'peak-catbird-459818-j8',
    authDomain: 'peak-catbird-459818-j8.firebaseapp.com',
    storageBucket: 'peak-catbird-459818-j8.firebasestorage.app',
  );
}
